### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Qodestackr** [pavlovicIvan/react-job-portal-app#1]
@pavlovicIvan since I find no way to chat via Github, I am thanking you as this project is cloned and ready to be used for my next project. I will contribute to this some day

**Comment by Qodestackr** [comment]
😂😂😂😂😂

**Comment by Qodestackr** [comment]
Why 😂😂🤔

**Comment by Qodestackr** [comment]
@pavlovicIvan . let's connect. Let's collaborate. I write python and React Stuff. GraphQL Firebase. FaunaDB etc

**Comment by pavlovicIvan** [comment]
Nice, let's connect on linkedIn :)

**Comment by Qodestackr** [comment]
For now check this. You are already a great writer.
https://github.com/section-io/engineering-education/

**Comment by Qodestackr** [comment]
They pay $ 250 each tech article you write

**Comment by Qodestackr** [comment]
I'm Wilson Njugia on LinkedIn @pavlovicIvan

**Comment by Qodestackr** [comment]
@ReactifyStudio 👋
